### ISSUE TITLE
Payload attribute SSE is fails to flush the stream

### ISSUE THREAD

**Issue by jinmel** [flashbots/optimism#5]
The op-node publishes PayloadAttributes upon receiving unsafe head from gossip channel. The server sent event library (https://github.com/r3labs/sse) seems to stall or fail to flush the stream buffer which in turn causes the builder to fail latest block.

**Comment by avalonche** [comment]
the prysm implementation uses github.com/gin-contrib/sse. Can try out if this library would work?

**Comment by jinmel** [comment]
Turns out it was a timeout enforced by the httputil package of optimism
https://github.com/ethereum-optimism/optimism/blob/ed817c7c2de0187190d84f1e065760f7606a53f6/op-service/httputil/server.go#L32

I fixed it by setting 0 to ReadTimeout and IdleTimeout
