### ISSUE TITLE
Use versioned block contents for deneb payload data

### ISSUE THREAD

**Issue by jinmel** [flashbots/optimism#8]
Use [versioned block contents](https://github.com/attestantio/go-builder-client/blob/master/api/versionedsubmitblindedblockresponse.go) for sending deneb payloads to sequencer

**Comment by avalonche** [comment]
the optimism stack does not accept [blob transactions](https://github.com/ethereum-optimism/op-geth/blob/optimism/eth/api_backend.go#L296-L298) so I don't understand the use case for using the versioned block contents? Blobs and related fields can just be hardcoded to be empty / 0 values

**Comment by avalonche** [comment]
completed
